import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useRouter
 } from 'next/router'
export default function Home() {
  const router = useRouter()
  return (
    <div className={styles.container}>
      <Head>
        <title>Twitter devs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Twitter devs
        </h1>
        <Link href={"/timeline"} >
          <a>
            Ultimos tweets
          </a>
        </Link>
      </main>
    </div>
  )
}
