import { useEffect } from "react";
import Head from "next/head";
import styles from "styles/Home.module.css";
import Image from "next/image";
import Button from "components/Button/Button";
import GithubLogo from "components/Icons/GithubLogo";
// eslint-disable-next-line import/no-absolute-path
import { loginWithGithub } from "/firebase/client";
import { useRouter } from "next/router";
import useUser from "hooks/useUser";

export default function Home() {
  const user = useUser();
  const router = useRouter();

  const handleClick = () => {
    loginWithGithub().catch((err) => console.log(err));
  };

  useEffect(() => {
    user && router.replace("/home");
  }, [user]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Twitter devs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.title_section}>
          <Image
            src="/app_logo.png"
            alt="Twitter devs logo"
            width="96"
            height="96"
          />
          <h1 className={styles.title}>Twitter devs</h1>
        </div>
        <a>👩🏻‍💻 Descubre de que hablan lxs desarroladorxs hoy 👨🏻‍💻</a>
        {user === null ? (
          <Button onClick={handleClick}>
            <GithubLogo width={32} height={32} />
            Login with Github
          </Button>
        ) : (
          <img src="/spinner.gif" />
        )}
      </main>
    </div>
  );
}
